#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# setup.sh — turn .env into generated, gitignored Terraform config.
#
# Idempotent: re-run it any time you change .env. It never edits committed
# files; it only writes *_override.tf and zz_generated.auto.tfvars (both
# gitignored) into each environment directory.
# ---------------------------------------------------------------------------
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENVIRONMENTS=(dev staging prod)

if [[ ! -f "${ROOT}/.env" ]]; then
  echo "No .env found. Run: cp .env.example .env && edit it, then re-run ./setup.sh" >&2
  exit 1
fi

# shellcheck disable=SC1091
set -a; source "${ROOT}/.env"; set +a

# Defaults for anything the user left unset.
: "${AWS_REGION:=eu-west-2}"
: "${CLUSTER_DOMAIN:=example.com}"
: "${GITOPS_REPO_URL:=https://github.com/your-org/eks-gitops-starter.git}"
: "${ENABLE_TAILSCALE:=false}"
: "${USE_HCP_BACKEND:=false}"
: "${TF_STATE_LOCK_TABLE:=eks-gitops-starter-tf-locks}"

note() { printf '  %s\n' "$*"; }

for env in "${ENVIRONMENTS[@]}"; do
  dir="${ROOT}/infra/environments/${env}"
  [[ -d "${dir}" ]] || { echo "skip: ${dir} does not exist yet"; continue; }
  echo "==> ${env}"

  # --- backend -------------------------------------------------------------
  backend_file="${dir}/backend_override.tf"
  if [[ "${USE_HCP_BACKEND}" == "true" ]]; then
    : "${HCP_ORG:?USE_HCP_BACKEND=true but HCP_ORG is not set in .env}"
    cat >"${backend_file}" <<EOF
# GENERATED by setup.sh — do not commit. HCP Terraform backend.
terraform {
  cloud {
    organization = "${HCP_ORG}"
    workspaces { name = "${env}_infra" }
  }
}
EOF
    note "backend: HCP Terraform (org=${HCP_ORG}, workspace=${env}_infra)"
  elif [[ -n "${TF_STATE_BUCKET:-}" ]]; then
    cat >"${backend_file}" <<EOF
# GENERATED by setup.sh — do not commit. S3 + DynamoDB backend.
terraform {
  backend "s3" {
    bucket         = "${TF_STATE_BUCKET}"
    key            = "${env}/terraform.tfstate"
    region         = "${AWS_REGION}"
    dynamodb_table = "${TF_STATE_LOCK_TABLE}"
    encrypt        = true
  }
}
EOF
    note "backend: S3 (bucket=${TF_STATE_BUCKET}, key=${env}/terraform.tfstate)"
  else
    rm -f "${backend_file}"
    note "backend: local state (set TF_STATE_BUCKET or USE_HCP_BACKEND for remote)"
  fi

  # --- generated variables -------------------------------------------------
  cat >"${dir}/zz_generated.auto.tfvars" <<EOF
# GENERATED by setup.sh — do not commit.
region           = "${AWS_REGION}"
cluster_domain   = "${CLUSTER_DOMAIN}"
gitops_repo_url  = "${GITOPS_REPO_URL}"
enable_tailscale = ${ENABLE_TAILSCALE}
EOF
  [[ -n "${AWS_ACCOUNT_ID:-}" ]] && echo "aws_account_id   = \"${AWS_ACCOUNT_ID}\"" >>"${dir}/zz_generated.auto.tfvars"
  note "wrote zz_generated.auto.tfvars"
done

echo
echo "Done. Next:"
echo "  task infra:plan ENV=dev     # or ENV=staging / prod"
echo "  task kind-up                # local, no AWS"
