apiVersion: v1
kind: Service
metadata:
  name: backend-podinfo
  labels:
    app: backend-podinfo
spec:
  selector:
    app: backend-podinfo
  ports:
    - name: http
      port: 9898
      targetPort: http
